///
/// Auto Generated by GenerateFileNameList
///
namespace GenerateFileList
{
    public static class FileNames
    {
        public static readonly string name1 = "name1.png";
        public static readonly string name2 = "name2.png";
        public static readonly string name31 = "name3 1.png";
        public static readonly string testname3 = "SubFolder/testname3.png";
    }
}