///
/// Auto Generated by GenerateFileNameList
///

using System.Collections.Generic;
namespace GenerateFileList
{
    public static class FileNamesDictionary
    {
         public static Dictionary<string, string> nameList = new Dictionary<string, string>
            {
                {"name1", "name1.png"},
                {"name2", "name2.png"},
                {"name31", "name3 1.png"},
                {"testname3", "SubFolder/testname3.png"},
            };
    }
}